name: HeckeCategories
version: "2023.02-03"
license: "GPL-2.0-or-later"
date: 2023-02-24
description: |
    Categorification of Hecke algebras

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/
    - name: Daniel Juteau
      url: https://www.lamfa.u-picardie.fr/annuaire/danjuteau
    - name: Damián de la Fuente
      url: https://github.com/damian-delafuente/

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/
    - name: Daniel Juteau
      url: https://www.lamfa.u-picardie.fr/annuaire/danjuteau
    - name: Damián de la Fuente
      url: https://github.com/damian-delafuente/

GAP: ">= 4.12.1"

needed-pkgs:
    - name: "RingsForHomalg"
      version: ">= 2023.02-02"
      url: "https://homalg-project.github.io/pkg/RingsForHomalg"
    - name: "CAP"
      version: ">= 2023.02-09"
      url: "https://homalg-project.github.io/pkg/CAP"
    - name: "MonoidalCategories"
      version: ">= 2023.02-04"
      url: "https://homalg-project.github.io/pkg/MonoidalCategories"
    - name: "FreydCategoriesForCAP"
      version: ">= 2023.02-01"
      url: "https://homalg-project.github.io/pkg/FreydCategoriesForCAP"

www: https://homalg-project.github.io/pkg/HeckeCategories
readme: README.md
packageinfo: https://homalg-project.github.io/HeckeCategories/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/HeckeCategories/releases/download/v2023.02-03/HeckeCategories-2023.02-03.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/HeckeCategories/releases/download/v2023.02-03/HeckeCategories-2023.02-03.zip

pdf: https://github.com/homalg-project/HeckeCategories/releases/download/v2023.02-03/HeckeCategories-2023.02-03.pdf

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BJF23</span>]   <b class='BibAuthor'>Barakat, M., Juteau, D. and de la Fuente, D.</b>,
     <i class='BibTitle'>HeckeCategories, Categorification of Hecke algebras,
             Version 2023.02-03</i>
     (<span class='BibYear'>2023</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/pkg/HeckeCategories">https://homalg-project.github.io/pkg/HeckeCategories</a></span>.
    </p>
    

bibtex: |
    @misc{ HeckeCategories2023.02-03,
      author =           {Barakat, M. and Juteau, D. and de la Fuente, D.},
      title =            {{HeckeCategories}, Categorification of Hecke algebras,
                          {V}ersion 2023.02-03},
      month =            {Feb},
      year =             {2023},
      note =             {GAP package},
      howpublished =     {\href
                          {https://homalg-project.github.io/pkg/HeckeCategories}
                          {\texttt{https://homalg-project.github.io/}\discretionary
                          {}{}{}\texttt{pkg/}\discretionary
                          {}{}{}\texttt{HeckeCategories}}},
      printedkey =       {BJF23}
    }

